//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_380.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCode
    {
        public int CouponICoded { get; set; }
        public string Code { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<int> UsageLimit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
    }
}
