//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_380.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantityt { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual UserName UserName { get; set; }
    }
}
