//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_380.Models.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sandhya_380Entities1 : DbContext
    {
        public Sandhya_380Entities1()
            : base("name=Sandhya_380Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<tblCouponCodeMaster> tblCouponCodeMaster { get; set; }
        public virtual DbSet<UserName> UserName { get; set; }
    }
}
